name: flutter_emart1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  velocity_x: ^4.3.1
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
#  cloud_functions: ^4.0.0
#  http: ^0.13.0
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
#  fl_chart: ^0.55.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - lib/services/category_model.json

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
